Live merge. Enterprise to master.
travis-ci/travis-live pull request #52
Opened 2024-03-18 09:51 UTC by AdamZielinski-Devtactics

2024-03-19 13:14 UTC, gbarc-dt commented on Gemfile
> +gem 'sentry-raven'
sentry-raven is now sentry-ruby

2024-03-19 13:14 UTC, gbarc-dt commented on Makefile2
this one we don't need :P

2024-03-19 13:16 UTC, AdamZielinski-Devtactics commented on Makefile2
Fixed.

2024-03-28 07:35 UTC, GbArc requested changes

2024-03-28 07:35 UTC, GbArc commented on .travis.yml
>        script: make ship
add dist: focal

2024-03-28 07:35 UTC, GbArc commented on Makefile2
this file isn't needed

2024-07-23 15:12 UTC, DominikAlberski commented
Same as #56 merged in #57

2024-07-23 15:12 UTC, closed without merging